error goes to stderr
Co-authored-by: Pedro Tashima <tithe.coup0l@icloud.com>

diff --git a/scripts/package-ci b/scripts/package-ci
--- a/scripts/package-ci
+++ b/scripts/package-ci
@@ -29,7 +29,7 @@ log_skip() {
 }
 
 log_error() {
-    echo -e "${RED}[FAIL]${RESET} $1"
+    echo -e "${RED}[FAIL]${RESET} $1" >&2
 }
 
 # Validate clean git state
