changing read bumped version strategy for auto-bump GHA job

diff --git a/.github/workflows/auto-bump.yaml b/.github/workflows/auto-bump.yaml
--- a/.github/workflows/auto-bump.yaml
+++ b/.github/workflows/auto-bump.yaml
@@ -33,16 +33,36 @@ jobs:
         run: |
           git checkout -b "auto-bump_${{ env.CHART }}"
 
-      - name: make chart-bump
+      - name: make pull-scripts
         run: |
-          echo "make chart-bump package=${{ env.CHART }} branch=${{ env.BRANCH }}"
-          last_line=$(make chart-bump package="${{ env.CHART }}" branch="${{ env.BRANCH }}" | tail -n 1)
-          echo "new_version=$last_line" >> $GITHUB_ENV
-          echo "new_version (in make step): $last_line" # For debugging in this step
+          echo "make pull-scripts"
+          make pull-scripts
 
-      - name: Echo new_version (separate step)
+      - name: chart-bump
         run: |
-          echo "new_version (in echo step): ${{ env.new_version }}"
+          ./bin/charts-build-scripts chart-bump --package="${{ env.CHART }}" --branch="${{ env.BRANCH }}"
+
+      - name: read bump version from json file
+        id: read_bump_version
+        run: |
+          echo "Reading data from config/bump.json"
+          JSON_FILE="config/bump.json"
+
+          if [[ ! -f "$JSON_FILE" ]]; then
+            echo "Error: $JSON_FILE not found!"
+            exit 1
+          fi
+
+          NEW_VERSION=$(jq -r '.new_version' "$JSON_FILE")
+          if [[ -z "$NEW_VERSION" || "$NEW_VERSION" == "null" ]]; then
+            echo "Error: Could not read '.new_version' or value is null/empty in $JSON_FILE"
+            exit 1
+          fi
+
+          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
+
+          CHARTS_ARRAY_JSON=$(jq -c '.charts' "$JSON_FILE")
+          echo $CHARTS_ARRAY_JSON
 
       - name: Git status
         run: |
@@ -58,6 +78,7 @@ jobs:
           secrets: |
             secret/data/github/repo/${{ github.repository }}/github/app-credentials appId | APP_ID ;
             secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATE_KEY
+
       - name: Create App Token
         uses: actions/create-github-app-token@v1
         id: app-token
@@ -80,4 +101,4 @@ jobs:
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          gh pr create --base ${{ env.BRANCH }} --head "auto-bump_${{ env.CHART }}" --title "[${{ env.BRANCH }}] auto: ${{ env.CHART }} ${{ env.new_version }}" --body-file '.github/auto_bump_template.md'
+          gh pr create --base ${{ env.BRANCH }} --head "auto-bump_${{ env.CHART }}" --title "[${{ env.BRANCH }}] auto: ${{ env.CHART }} ${{ steps.read_bump_version.outputs.version }}" --body-file '.github/auto_bump_template.md'
